### ISSUE TITLE
Works on FX705DU

### ISSUE THREAD

**Issue by Saancreed** [hackbnw/faustus#15]
Arch Linux, kernel version `5.4.13-zen1-1-zen`

Filtered `dmidecode` output:
```
BIOS Information
        Vendor: American Megatrends Inc.
        Version: FX705DU.308
        Release Date: 09/19/2019
--
Base Board Information
        Manufacturer: ASUSTeK COMPUTER INC.
        Product Name: FX705DU
        Version: 1.0
```

DSDT file: [dsdt.aml.gz](https://github.com/hackbnw/faustus/files/4099597/dsdt.aml.gz)

**Comment by hackbnw** [comment]
Thank you for the feedback! I included your model in the list.
