### ISSUE TITLE
Works on FX705GM.305

### ISSUE THREAD

**Issue by Eks2** [hackbnw/faustus#19]
Thank you, it works great.
Running on 5.3.18-1-MANJARO
```
BIOS Information
        Vendor: American Megatrends Inc.
        Version: FX705GM.305
        Release Date: 05/31/2019
--
Base Board Information
        Manufacturer: ASUSTeK COMPUTER INC.
        Product Name: FX705GM
        Version: 1.0
```

[dsdt.aml.tar.gz](https://github.com/hackbnw/faustus/files/4162183/dsdt.aml.tar.gz)

**Comment by hackbnw** [comment]
Thank you for the feedback @Eks2 ! I've added you model to the list.
