### ISSUE TITLE
Works on FX505DV

### ISSUE THREAD

**Issue by nuzly** [hackbnw/faustus#20]
BIOS Information
        Vendor: American Megatrends Inc.
        Version: FX505DV.303
        Release Date: 09/19/2019
Base Board Information
        Manufacturer: ASUSTeK COMPUTER INC.
        Product Name: FX505DV
        Version: 1.0

NAME="Ubuntu"
VERSION="19.10 (Eoan Ermine)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 19.10"
VERSION_ID="19.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan

Linux kernel: 5.3.0-29-generic

**Comment by hackbnw** [comment]
Thank you @nuzly ! Model is added to the list.
