### ISSUE TITLE
Fan mode file changed

### ISSUE THREAD

**Issue by Xabifk** [hackbnw/faustus#31]
The fan mode file has changed from `/sys/devices/platform/faustus/fan_mode` to `/sys/devices/platform/faustus/fan_boost_mode`

**Comment by yaliv** [comment]
> The fan mode file has changed from `/sys/devices/platform/faustus/fan_mode` to `/sys/devices/platform/faustus/fan_boost_mode`

Confirm that.
But although I hear speed changes to my fan after pressing `Fn`+`F5`, the value of `/sys/devices/platform/faustus/fan_boost_mode` is always `0`.
:man_shrugging:

**Comment by hackbnw** [comment]
The new name is correct one, this is how it's named in the mainline driver and by the vendor, as opposed to the fan_mode which usually means automatic or manual. It was an error on my part. Sorry for that. I will update the README.

**Comment by hackbnw** [comment]
@yaliv are you sure? what does it say in `dmesg`, should be the following

```
[96234.887932] faustus: Set fan boost mode: 0
[96236.838525] faustus: Set fan boost mode: 1
[96237.708032] faustus: Set fan boost mode: 2
[96238.682679] faustus: Set fan boost mode: 0
```

**Comment by hackbnw** [comment]
@yaliv The mainline driver has separate option for your laptop which is named `throttle_thermal_policy` which has only silent and default mode if I'm correct. You should have `/sys/devices/platform/faustus/throttle_thermal_policy` file where the value changes (probably there might be laptops with both options present simultaneously?)

**Comment by Xabifk** [comment]
@hackbnw I can confirm that's how it works for me
Maybe add a note in the README?

**Comment by hackbnw** [comment]
Thanks for noticing! Just updated the README.

**Comment by yaliv** [comment]
> @yaliv The mainline driver has separate option for your laptop which is named `throttle_thermal_policy` which has ~only silent and default mode~ always 3 modes. You should have `/sys/devices/platform/faustus/throttle_thermal_policy` file where the value changes (probably there might be laptops with both options present simultaneously?)

Great! I can see value changes in `throttle_thermal_policy`:
```sh
$ cat /sys/devices/platform/faustus/throttle_thermal_policy
0
$ cat /sys/devices/platform/faustus/throttle_thermal_policy
1
$ cat /sys/devices/platform/faustus/throttle_thermal_policy
2
```
:+1:

**Comment by Xabifk** [comment]
As the README was updated and everything seems clear I'll close this issue
