### ISSUE TITLE
Can't control rgb on fx505dt

### ISSUE THREAD

**Issue by n1gh7maan** [hackbnw/faustus#34]
I can't control for some reason my keyboard. Every file in  `/sys/devices/platform/faustus/kbbl` has 00 value. When i try to change any file in that directory, the value switches back to 00. After installation of the driver I was able to properly control leds. 
OS: Manjaro 20.04
kernel: 5.6.8-1-MANJARO
FX505DT, bios 308

**Comment by n1gh7maan** [comment]
Nevermind, I figured it out. I forgot to set kbbl_flags. 
Is it just me or rgb lights in bios are brighter than in windows/linux?

**Comment by TaherPatan** [comment]
> Nevermind, I figured it out. I forgot to set kbbl_flags.
> Is it just me or rgb lights in bios are brighter than in windows/linux?

Are you able to control the fans?

**Comment by n1gh7maan** [comment]
> Are you able to control the fans?
yes

**Comment by TaherPatan** [comment]
> > Are you able to control the fans?
> 
> yes

You have asus fx505dt with gtx 1650 right? Did you change any settings to be able to control fans? Is there any indication that the fan speed changed?

**Comment by n1gh7maan** [comment]
for me fn+f5 works after installing this driver. You can check whether pressing these buttons work by running `cat /sys/devices/platform/faustus/throttle_thermal_policy`
