### ISSUE TITLE
Works on FX705DT

### ISSUE THREAD

**Issue by SphericalKat** [hackbnw/faustus#37]
I've tested the latest version on `FX705DT`, bios version `FX705DT.308` running `Arch Linux` with kernel `5.6.13-arch1-1`. RGB, brightness and fan control work well.

```
➜  TUF-Control git:(master) sudo dmidecode | grep "BIOS Inf\|Board Inf" -A 3
BIOS Information
	Vendor: American Megatrends Inc.
	Version: FX705DT.308
	Release Date: 09/19/2019
--
Base Board Information
	Manufacturer: ASUSTeK COMPUTER INC.
	Product Name: FX705DT
	Version: 1.0
```

**Comment by Syzygianinfern0** [comment]
@ATechnoHazard have you gotten the GPU Drivers to work well with Prime Offloading in this laptop on Arch Linux?

**Comment by ATechnoHazard** [comment]
Nope, I'm just using the nvidia for everything.

**Comment by hackbnw** [comment]
Thanks for feedback!
