### ISSUE TITLE
Works with FX505DT

### ISSUE THREAD

**Issue by ferretwithaberet** [hackbnw/faustus#41]
**Output for `sudo dmidecode | grep "BIOS Inf\|Board Inf" -A 3`**
```
BIOS Information
        Vendor: American Megatrends Inc.
        Version: FX505DT.310
        Release Date: 12/24/2019
--
Base Board Information
        Manufacturer: ASUSTeK COMPUTER INC.
        Product Name: FX505DT
        Version: 1.0
```
![image](https://user-images.githubusercontent.com/46427158/85942590-dd44d300-b932-11ea-89ec-97dfd2548b3c.png)

**Comment by RadoiAndrei** [comment]
![image](https://user-images.githubusercontent.com/46427158/85942658-580dee00-b933-11ea-9624-040bc62afeb4.png)

Also, this means I fixed the graphic cards issue, right? I am still quite a newbie when it comes to linux.

**Comment by icodelifee** [comment]
is the display flickering for you?

**Comment by RadoiAndrei** [comment]
> is the display flickering for you?
> 

I did not experience any flickering yet.

**Comment by icodelifee** [comment]
its supposed to happen display goes to sleep and wakes up!
oh so you have different panel?
mine only has 48hz and 120hz

**Comment by RadoiAndrei** [comment]
> its supposed to happen display goes to sleep and wakes up!
> oh so you have different panel?
> mine only has 48hz and 120hz

Nope, does not happen to me.

**Comment by sticsk** [comment]
It is working for me, using [https://github.com/rublag/faustus](url) this repo, I have the same laptop as you

**Comment by icodelifee** [comment]
> It is working for me, using [https://github.com/rublag/faustus](url) this repo, I have the same laptop as you

what is working for you in your repo?

**Comment by sticsk** [comment]
> > It is working for me, using [https://github.com/rublag/faustus](url) this repo, I have the same laptop as you
> 
> what is working for you in your repo?

rgb lights works

Fan Works but it takes a bit of time to realise, and when i hit `dmesg -wH` it says `Failed to set throttle thermal policy`, but I did a benchmark test with Unigine Heaven and the fans were going off when on boost mode so it's a good sign, but I don't use the boost mode I use silent mode for battery, I'll check the clock speed later to see if Silent it's working.

I don't know what's modified in rublag's repo beacuse I don't understand where to check, but hackbnw's fan modes didnt work.


By the way my bios version is FX505DT.310 and kernel is linux57

**Comment by icodelifee** [comment]
> > > It is working for me, using [https://github.com/rublag/faustus](url) this repo, I have the same laptop as you
> > 
> > 
> > what is working for you in your repo?
> 
> rgb lights works
> 
> Fan Works but it takes a bit of time to realise, and when i hit `dmesg -wH` it says `Failed to set throttle thermal policy`, but I did a benchmark test with Unigine Heaven and the fans were going off when on boost mode so it's a good sign, but I don't use the boost mode I use silent mode for battery, I'll check the clock speed later to see if Silent it's working.
> 
> I don't know what's modified in rublag's repo beacuse I don't understand where to check, but hackbnw's fan modes didnt work.
> 
> By the way my bios version is FX505DT.310 and kernel is linux57

and you have the same display as @RadoiAndrei ?

**Comment by sticsk** [comment]
Yep, same gpu/cpu with non-free drivers

**Comment by icodelifee** [comment]
> Yep, same gpu/cpu with non-free drivers

hmm, weird i guess only indian and some eu variants have display with 48hz and 120hz mode!

**Comment by sticsk** [comment]
> > Yep, same gpu/cpu with non-free drivers
> 
> hmm, weird i guess only indian and some eu variants have display with 48hz and 120hz mode!
> 

The guy's Romanian and that version of the laptop comes with 60Hz, the 120Hz is expensive with i7 or the ryzen equivalent(i forgot)

**Comment by ferretwithaberet** [comment]
It is no surprise, but it works on EndeavourOS too:
![image](https://user-images.githubusercontent.com/46427158/104988758-8f540180-5a21-11eb-8ee7-5ad2dde3c0ed.png)

**Comment by hackbnw** [comment]
Thanks!
