### ISSUE TITLE
Works on FX505DT

### ISSUE THREAD

**Issue by bjaenichen** [hackbnw/faustus#57]
BIOS Information
        Vendor: American Megatrends Inc.
        Version: FX505DT.310
        Release Date: 12/24/2019
--
Base Board Information
        Manufacturer: ASUSTeK COMPUTER INC.
        Product Name: FX505DT
        Version: 1.0
:\~> cat /etc/os-release 
NAME="openSUSE Leap"
VERSION="15.2"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.2"
PRETTY_NAME="openSUSE Leap 15.2"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.2"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
:\~> uname -a
Linux voyager 5.3.18-lp152.57-default #1 SMP Fri Dec 4 07:27:58 UTC 2020 (7be5551) x86_64 x86_64 x86_64 GNU/Linux

**Comment by hackbnw** [comment]
Thanks!
