### ISSUE TITLE
Works on model FX505GD

### ISSUE THREAD

**Issue by gerhardusmuller** [hackbnw/faustus#7]
Board information:

dmidecode | grep "BIOS Inf\|Board Inf" -A 3 
BIOS Information
        Vendor: American Megatrends Inc.
        Version: FX505GD.304
        Release Date: 01/30/2019
--
Base Board Information
        Manufacturer: ASUSTeK COMPUTER INC.
        Product Name: FX505GD
        Version: 1.0

Thanks for the effort!

**Comment by hackbnw** [comment]
Thanks for report, included now!
